# Generated by Django 3.1.2 on 2020-12-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all4cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='number_of_rooms',
            new_name='num_of_bedrooms',
        ),
        migrations.RemoveField(
            model_name='house',
            name='floor_plan',
        ),
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='num_of_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
