# Generated by Django 3.1.2 on 2020-10-29 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all4cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('date', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('zipcode', models.CharField(default='', max_length=60, primary_key=True, serialize=False)),
                ('state', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_name', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('zipcode', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='All4Cats',
        ),
        migrations.AddField(
            model_name='price',
            name='zipcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all4cats.region'),
        ),
    ]
