# Generated by Django 3.1.2 on 2020-12-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all4cats', '0002_auto_20201202_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='num_of_bathrooms',
            field=models.FloatField(default=0.0),
        ),
    ]
