# Generated by Django 3.1.2 on 2020-10-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all4cats', '0002_auto_20201029_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('company', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('number_of_rooms', models.IntegerField()),
                ('floor_plan', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
