# Generated by Django 3.1.2 on 2020-12-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all4cats', '0002_auto_20201202_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='num_of_bathroom',
            new_name='num_of_bathrooms',
        ),
    ]
