# Generated by Django 3.1.2 on 2020-10-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all4cats', '0003_auto_20201030_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='price',
            name='zipcode',
            field=models.CharField(default='', max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('zipcode', 'date')},
        ),
    ]
