# Generated by Django 3.1.2 on 2020-10-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all4cats', '0004_auto_20201030_0426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
