# Generated by Django 3.1.2 on 2020-10-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all4cats', '0005_auto_20201030_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('company', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('number_of_rooms', models.IntegerField(default=0)),
                ('floor_plan', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(default='', max_length=60)),
                ('date', models.CharField(default='', max_length=200)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_name', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('zipcode', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
