# Generated by Django 3.1.2 on 2020-10-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all4cats', '0006_house_price_university'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('zipcode', 'date')},
        ),
    ]
