# Generated by Django 3.1.2 on 2020-11-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all4cats', '0007_auto_20201030_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='price',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
    ]
