# Generated by Django 3.1.2 on 2020-11-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all4cats', '0007_auto_20201030_0555'),
        ('all4cats', '0003_house'),
    ]

    operations = [
    ]
