# Generated by Django 3.1.2 on 2020-11-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all4cats', '0008_merge_20201101_0538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
